### ISSUE TITLE
Doesn't seem to work with search requests

### ISSUE THREAD

**Issue by plurch** [octokit/plugin-throttling.js#109]
Hello,

I am using this plugin along with the following dependencies:

```
    "@octokit/plugin-retry": "^2.2.0",
    "@octokit/plugin-throttling": "^2.6.0",
    "@octokit/rest": "^16.28.7",
```

I tested timing between requests using the example in the [rest.js docs](https://octokit.github.io/rest.js/#pagination):

`for await (const response of octokit.paginate.iterator(options)) { ... `

However, it looks like my `search` requests are happening about 600ms - 800ms apart instead of the expected 2000ms.

I set a breakpoint [here](https://github.com/octokit/plugin-throttling.js/blob/master/lib/wrap-request.js#L34) and it looks like `isSearch` is `false` since `options.url` has a value like `https://api.github.com/search/users?q= ...`, so `startsWith('/search/')` will not work as expected.

So it seems like the issue is that the code expects `options.url` to be the path only, but it is actually the full URL. This might also be an issue with GraphQL requests since it is using `startsWith('/graphql')`, but I haven't tested that myself.

Please let me know if I can provide any other information that would be helpful. Thanks 🙂

**Comment by SGrondin** [comment]
Excellent debugging, I think you've exactly identified what the problem is. I'll take a look and release a fix soon, probably this weekend.

**Comment by plurch** [comment]
@SGrondin Great, thanks!

**Comment by SGrondin** [comment]
@plurch which version of Node are you using? If you're running this in the browser, which build system did you use (e.g. Webpack, etc)?

I'm unable to reproduce `options.url` being a full url.

And since the `url` module now has 2 very different versions (one compatible with the new browser `URL` object, and one that's not), I want to make sure I understand all the tradeoffs before we add any package or feature-detection logic.

@gr2m does octokit already use an url parser somewhere?

If we need to add an url parser, which one of these options should we pick?
1. Detect if `URL` exists and use it if it does. If not, require `url` and use that. Older browsers will not work: https://caniuse.com/#feat=url
2. Add this dependency, use it everywhere: https://www.npmjs.com/package/url Simplest option, but adds to the bundle size.
3. Some error-prone regex or `.contains()`. [As a fan of regular expressions](https://github.com/octokit/plugin-throttling.js/blob/master/lib/route-matcher.js) I'm not opposed to using them for the right job, but this isn't the right job in my opinion. Still, it could solve the problem quickly and easily.

**Comment by plurch** [comment]
@SGrondin , this is how I am using it:

```
$ node -v
v10.16.2
$ npm -v
6.10.3
```

```typescript
import * as OctokitRest from '@octokit/rest';
import * as OctokitRetry from '@octokit/plugin-retry';
import * as OctokitThrottling from '@octokit/plugin-throttling';
const Octokit = OctokitRest.plugin([OctokitThrottling, OctokitRetry]);

//...

const octokit = new Octokit({
  auth: {
    clientId: process.env.GH_CLIENT_ID,
    clientSecret: process.env.GH_CLIENT_SECRET
  },
  throttle: {
    onRateLimit: (retryAfter, options) => {
      console.warn(`Request quota exhausted for request ${options.method} ${options.url}`)

      if (options.request.retryCount === 0) { // only retries once
        console.log(`Retrying after ${retryAfter} seconds!`)
        return true
      }
    },
    onAbuseLimit: (retryAfter, options) => {
      // does not retry, only logs a warning
      console.warn(`Abuse detected for request ${options.method} ${options.url}`)
    }
  },
  userAgent: 'My App',
});

   const options = octokit.search.users.endpoint.merge({ ...  });

  for await (const userData of octokit.paginate.iterator(options)) { ... }


```


Maybe using `auth.clientId` and `auth.clientSecret` somehow causes it to use the full URL? Or it could be `endpoint.merge()` ?

Let me know if I can provide any other information.

**Comment by gr2m** [comment]
sorry I’m out today and tomorrow, but the url option can be a full URL, e.g. when doing octokit.request(‘https://api.github.com/foo/bar’)

I think what commonly creates full urls is pagination, as we pass the url from the link headers directly

**Comment by SGrondin** [comment]
Ah yeah, that's it @gr2m . Thanks to both of you for the info. @gr2m please let me know how you want to proceed with url parsing.

**Comment by gr2m** [comment]
Ideally native URL object in browser, then polyfill in Node. Minimal bundle size for browsers is a priority

**Comment by gr2m** [comment]
@SGrondin @plurch is this problem resolved?

**Comment by allanlw** [comment]
I ran into this today when using https://github.com/octokit/plugin-paginate-rest.js/ in combination with searches and the current version of both and octokit.

**Comment by gr2m** [comment]
@allanlw could you share a minimal code example please?

**Comment by allanlw** [comment]
@gr2m here's a minimal example in typescript:
``` ts
import { promises as fs } from "fs";
import { Octokit } from "@octokit/rest";
import { paginateRest } from "@octokit/plugin-paginate-rest";
import { throttling } from "@octokit/plugin-throttling";

async function main() {
  const token = (
    await fs.readFile("token.txt", {
      encoding: "utf-8",
    })
  ).trim();

  const octokitWithPlugins = Octokit.plugin(paginateRest, throttling);

  const octokit = new octokitWithPlugins({
    auth: token,
    throttle: {
      onRateLimit: (retryAfter: number, options: any, octokit: Octokit) => {
        octokit.log.warn(
          `Request quota exhausted for request ${options.method} ${options.url}`
        );
        return false;
      },
      onAbuseLimit: (retryAfter: number, options: any, octokit: Octokit) => {
        octokit.log.warn(
          `Abuse detected for request ${options.method} ${options.url}`
        );
        return false;
      },
    },
  });

  for await (const response of octokit.paginate.iterator("GET /search/code", {
    q: "language:json devDependencies",
    per_page: 10,
  })) {
    console.log(new Date(), response.url);
  }
}

main().catch((err) => console.error(err));
```

package.json:
```
  "devDependencies": {
    "@types/node": "^14.14.41",
    "prettier": "^2.2.1",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "@octokit/plugin-paginate-rest": "^2.13.3",
    "@octokit/plugin-throttling": "^3.4.1",
    "@octokit/rest": "^18.5.3"
  }
```
