### ISSUE TITLE
Failing with "API rate limit exceeded"

### ISSUE THREAD

**Issue by sbender9** [octokit/plugin-throttling.js#124]
I'm calling `octokit.search.issuesAndPullRequests` many times. 

When it retries it fails completely:

```
Request quota exhausted for request GET /search/issues
Retrying after 0 seconds!
{ HttpError: API rate limit exceeded for user ID 7853683.
    at response.text.then.message (/usr/local/src/github-create-release/node_modules/@octokit/request/lib/request.js:56:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  status: 403,
  headers:
```

**Comment by gr2m** [comment]
Search requests have a very low rate limit, try to limit your calls to it.

If you think it's a problem with this plugin, can you provide a minimal code snippet to reproduce the problem you are seeing?
