### ISSUE TITLE
Cache the Bottleneck instances outside of the plugin

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-throttling.js#21]
### Use case

[Probot](https://github.com/probot/probot) is creating separate instances for each webhook event it receives from GitHub. In order for the throttling to be persist, we started caching the entire Octokit instances (https://github.com/probot/probot/commit/2532d617e3c96a7ae51adec22af73d9f3d839d01).

That works okay but increases the memory usage of Probot apps unnecessarily. It would be much more memory efficient to only cache the bottleneck states or instances in memory instead

**Comment by SGrondin** [comment]
This is done 🎉
