### ISSUE TITLE
[GraphQL] 401 response not handled correctly in case of `POST /graphql` requests

### ISSUE THREAD

**Issue by Chocrates** [octokit/plugin-throttling.js#229]
👋 Hi All,

Based on this code https://github.com/octokit/plugin-throttling.js/blob/5f65acb2bc9171777e195fc07448d373fcbb49f7/src/index.ts#L114 it looks like throttling is disabled for GraphQL queries.  
This has the side effect of eating errors that the graphql endpoints would throw.  
What would it take to enable throttling for graphql endpoints as well as rest?

**Comment by gr2m** [comment]
For context: GraphQL throttling has been introduced via https://github.com/octokit/plugin-throttling.js/pull/75 /cc @SGrondin

**Comment by gr2m** [comment]
@Chocrates could you share a test case to reproduce the problem with the swallowed errors?

I'm pretty sure that GraphQL throttling is implemented, did you run into problem with that?

**Comment by Chocrates** [comment]
Nope I am going insane.  I am not seeing the same thing I saw this morning.  
If I run this code (notice the missing token), the rate limit handler fires:

```
const { throttling } = require("@octokit/plugin-throttling");
const { Octokit } = require('@octokit/rest')
const MyOctokit = Octokit
  .plugin(throttling)

  async function main() {
    const client =  new MyOctokit({
      auth: "token ",
      throttle: {
        onRateLimit: (retryAfter, options) => {
          console.warn(`Request quota exhausted for request ${options.method} ${options.url}`);
          console.log(`Retrying after ${retryAfter} seconds! Retry Count: ${options.request.retryCount}`);
          return true;
        },
        onAbuseLimit: (retryAfter, options) => {
          console.warn(`Abuse detected for request ${options.method} ${options.url}`);
        }
      }
    });


        const query = `query {  
          organization(login: "chocratestestorg") {
            repositories(first: 100, after: null) {
              nodes {
                nameWithOwner
                createdAt
                pushedAt
              }
              totalCount
              pageInfo {
                hasNextPage
                endCursor
              }
            }
          }
        }`
        try {
          const results = await client.graphql(query)
          console.log(JSON.stringify(results))
         }catch(error){
           console.log(error);
         }
}

if (require.main == module){
    main();
}

module.exports = main;
```

I think I remember this morning the `http 401` wasn't getting reported, but the failed handler is catching it.

**Comment by Chocrates** [comment]
Ok so I think the "problem" is that the `/graphql` endpoint can throw an `HTTP 401` on invalid credentials and the if statement won't return and will instead handle the request like an `403`.

**Comment by gr2m** [comment]
I think I got it now. I created a minimal reproducible test case on RunKit:
https://runkit.com/gr2m/octokit-plugin-throttling-js-229/1.0.0

It logs 

> "Request quota exhausted for request POST /graphql"
> "Retrying after 3600 seconds! Retry Count: 0"

Which doesn't make any sense. We don't handle the `401` response correctly in case of graphql requests

**Comment by gr2m** [comment]
I don't have bandwith right now to work on this myself. Maybe @SGrondin finds time.

I'd be happy to review a pull request from you or anyone who'd like to give it a try though

**Comment by copperwall** [comment]
I'm down to give this a try!
