### ISSUE TITLE
Add @octokit/core as peerDependency

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-throttling.js#273]
This is a follow up issue to https://github.com/octokit/plugin-paginate-rest.js/issues/124#issuecomment-681019208
    
We need to add `@octokit/core` as a peerDependency to address a problem with yarn 2. It is something I planned to do anyway, but wanted to figure out automated testing to assure compatibility of the plugins with the latest `@octokit/core`.

I only want to define compatibility with the lowest version, in this case v3. Compare pull request https://github.com/octokit/plugin-paginate-rest.js/pull/130/files.

I would appreciate help, this is a great issue for a first-time contributor

**Comment by MichaelYogar** [comment]
Hi, I'm new to the open source community. I haven't made a contribution yet. I can try to do this if you can let me!

**Comment by gr2m** [comment]
@MichaelYogar Welcome to Octokit & Open Source :)
