### ISSUE TITLE
Abuse rate limitation needs an update

### ISSUE THREAD

**Issue by dontcallmedom** [octokit/plugin-throttling.js#437]
The current code to detect hitting of the abuse rate limit reads:
```typescript
      if (/\babuse\b/i.test(error.message)) {
```

As far as I can tell, nowadays, the error message from github reads:
`You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`

So the test should be updated accordingly.

**Comment by gr2m** [comment]
Woah, good catch! Thank you for reporting it and for sending a pull request!
