### ISSUE TITLE
Replace "abuse" language with "secondary"

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-throttling.js#439]
GitHub recently renamed "abuse limits" to "secondary rate limits":
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits

We should make sure to update our wording across all @octokit repositories accordingly

**Comment by oscard0m** [comment]
> GitHub recently renamed "abuse limits" to "secondary rate limits":
> https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits
> 
> We should make sure to update our wording across all @octokit repositories accordingly

Any kind of files (variable names?) or text files like `Markdown`, `JSON`, `HTML`?

Would the results of this search accurate enough?
https://github.com/search?q=org%3Aoctokit+abuse&type=code

**Comment by gr2m** [comment]
> Any kind of files (variable names?) or text files like `Markdown`, `JSON`, `HTML`?

Yes

> Would the results of this search accurate enough?
> https://github.com/search?q=org%3Aoctokit+abuse&type=code

Looks like a good start 👍🏼 
Do you want to look into it yourself?

**Comment by oscard0m** [comment]
> > Any kind of files (variable names?) or text files like `Markdown`, `JSON`, `HTML`?
> 
> 
> 
> Yes

So text files or code too?

> 
> 
> > Would the results of this search accurate enough?
> 
> > https://github.com/search?q=org%3Aoctokit+abuse&type=code
> 
> 
> 
> Looks like a good start 👍🏼 
> 
> Do you want to look into it yourself?

Sure!

**Comment by gr2m** [comment]
> So text files or code too?

everything

> > Do you want to look into it yourself?
> 
> Sure!

Awesome, thank you!

**Comment by 7upaesirik** [comment]
hows it going just heard bout this github learnin

**Comment by kaofelix** [comment]
We had an internal tool using the API that started triggering secondary rate limits recently without any code change in our part. We were using v3.4.0 of the plugin and finally we figured we had to update it to v3.5.2 to get the fix in #437. This caused the plugin not to be triggered anymore until we also updated @octokit/rest from v18.2.0 to v18.10.0. Just in case anyone else is fighting a similar issue and comes across this :)

**Comment by Sid-ah** [comment]
> > > Any kind of files (variable names?) or text files like `Markdown`, `JSON`, `HTML`?
> > 
> > 
> > Yes
> 
> So text files or code too?
> 
> > > Would the results of this search accurate enough?
> > 
> > 
> > > https://github.com/search?q=org%3Aoctokit+abuse&type=code
> > 
> > 
> > Looks like a good start 👍🏼
> > Do you want to look into it yourself?
> 
> Sure!

@oscard0m, did you have any luck replacing the naming?

**Comment by oscard0m** [comment]
> > > > Any kind of files (variable names?) or text files like `Markdown`, `JSON`, `HTML`?
> > > 
> > > 
> > > Yes
> > 
> > 
> > So text files or code too?
> > > > Would the results of this search accurate enough?
> > > 
> > > 
> > > > https://github.com/search?q=org%3Aoctokit+abuse&type=code
> > > 
> > > 
> > > Looks like a good start 👍🏼
> > > Do you want to look into it yourself?
> > 
> > 
> > Sure!
> 
> @oscard0m, did you have any luck replacing the naming?

Hey @Sid-ah , thanks getting back to me. I ended up not starting the PR for fixing this. I'm going to open a draft PR and tag you.

Regarding when we could land this I'm not sure. Octokit [is unmaintained since October 2021](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174) (including all the automation flows to keep the ecosystem up to date with most recent GitHub Open API changes). 

Fortunately, it seems that [there will be a team soon](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-2144643): 🍾 🥳
