### ISSUE TITLE
Distributed types seem to be incomplete

### ISSUE THREAD

**Issue by zephraph** [octokit/plugin-throttling.js#446]
I was configuring the throttle plugin essentially as it's written in the example in the readme and noticed `onRateLimit` and `onAbuseLimit` neither are inheriting the correct types. Opening up throttle's `index.d.ts` this is what I see:

```typescript
import { Octokit } from "@octokit/core";
export declare function throttling(octokit: Octokit, octokitOptions?: {}): {};
export declare namespace throttling {
    var VERSION: string;
    var triggersNotification: (string: string) => boolean;
}
```

I cloned the project and built from source just to verify the output. I'm seeing the same thing in `pkg/dist-types/index.d.ts` on build. I did look through the tests and it seems like the types pull through fine there... I'm not counting out user error here 😄 

Here's the code I'm using:

```typescript
import { Octokit } from "@octokit/rest";
import { retry } from "@octokit/plugin-retry";
import { throttling } from "@octokit/plugin-throttling";

//...

const RetryAndThrottleOctokit = Octokit.plugin(retry, throttling);
const octokit = new RetryAndThrottleOctokit({
  auth: process.env.GITHUB_TOKEN,
  throttle: {
    onRateLimit: (retryAfter, { method, url, request }) => {
      octokit.log.warn(`Request quota exhausted for request ${method} ${url}`);

      if (request.retryCount <= 2) {
        octokit.log.info(
          `Retrying after ${retryAfter} seconds! ${
            2 - request.retryCount
          } retries left.`
        );
        return true;
      }
      return false;
    },
    onAbuseLimit: (options) => {
      octokit.log.error(
        `Abuse detected for request ${options.method} ${options.url}, halting`
      );
      process.exit(1);
    },
  },
});

// ...
```

versions

```json
"@octokit/plugin-retry": "^3.0.9",
"@octokit/plugin-throttling": "^3.5.2",
"@octokit/rest": "^18.10.0",
```

**Comment by gr2m** [comment]
Setting option types from plugins is something that will get much better with the upcoming Octokit that we currently work on at https://github.com/octokit/octokit-next.js. Plugins will be able to extend the interface for the `Octokit` constructor options as seen here for example: https://github.com/octokit/octokit-next.js/blob/da2a4fbb681a18338214e7682c400946f54bb6fa/tests/js/plugins-and-defaults/plugins/with-options/index.d.ts#L3-L10

I agree the currently exported types are pretty much useless :D But I'd rather not try to make them more useful right now, it's been that way for a long time. I'd rather focus to get the new Octokit shipped

**Comment by zephraph** [comment]
Yep, sounds fine to me.

**Comment by JamiesWhiteShirt** [comment]
Leaving a hopefully helpful comment should anyone stumble upon this in the future.

The extension of `OctokitOptions` works in development but not when consuming the packages because `types.ts` is included in this package's development environment, but not when the package is consumed. It is possible to manually include `types.ts` as a consumer by including `@octokit/plugin-throttling/dist-types/types`.

A type reference directive somewhere in your code does the trick:
```typescript
/// <reference types="@octokit/plugin-throttling/dist-types/types"/>
```
