### ISSUE TITLE
Secondary Rate Limits For Code Search Always Retrying with Minimum of 5 Seconds

### ISSUE THREAD

**Issue by kaofelix** [octokit/plugin-throttling.js#454]
Hi folks,

I maintain a system that uses the code search API from Github and lately we started to get secondary rate limited very often. When looking at my logs, I see many retries after the default of 5 seconds which results in more rate limiting. From digging in the code for the plugin, I'm assuming we're probably never getting a `retry-after` header from Github, and that's why it keeps retrying with the minimum. The process we have is a long running batch process, so we wouldn't mind being rate limited and throttled, but right now we are seeing failures and flaky which seems to come from the repeated secondary rate limits being triggered. I'm looking for a way to configure the plugin that would throttle this calls in a way the API would find acceptable.

Thanks!

**Comment by edenhermelin** [comment]
hey 👋🏼 
I was wondering if there is an update on this one as it started happening to us as well.
Thanks!

**Comment by payne911** [comment]
I'm not having this issue: GitHub API returns the `retry-after` to me.

Maybe this can help you? https://github.com/useful-forks/useful-forks.github.io/commit/90dc02a951c78792b630b07fd584b2543b8f60b5

**Comment by gr2m** [comment]
Can you please share request IDs of requests that failed with a secondary rate limit error but without the `x-ratelimit-reset` header? I think this can indeed happen from my own experience, and I wonder if we should change the current behavior of retrying with the minimal 5s and rather start an exponential back-off or similar.

**Comment by payne911** [comment]
Exponential backoff is usually the standard: I think it'd be a good idea to implement that, provided it has a certain maximum cap to avoid timeouts.
However, I'm not sure where you folks get your default of 5s. On my end the code is behaving with a default of 60s for throttled retries.

**Comment by gr2m** [comment]
> I'm not sure where you folks get your default of 5s

[here](https://github.com/octokit/plugin-throttling.js/blob/5cb278e4b53cd8d7f5f0e5fae1290e1b96031760/src/index.ts#L143-L146). It seems that at least in some cases the `Retry-After` header is not set, in which case we default to 5s. 

What we should do instead is to start at 5s, but then back off exponentially until a request goes through.
