### ISSUE TITLE
Code points to a non-existing doc URL

### ISSUE THREAD

**Issue by payne911** [octokit/plugin-throttling.js#555]
https://github.com/octokit/plugin-throttling.js/blob/4d53e03bc43ccd5ad3f1cd9465838467e9d472da/src/index.ts#L86

Try out the link directly here: https://github.com/octokit/rest.js#throttling

**Comment by kfcampbell** [comment]
@payne911 I've created #559 to resolve this issue!

**Comment by payne911** [comment]
Yep! https://octokit.github.io/rest.js/v19#throttling looks like the right URL. Thanks!
