### ISSUE TITLE
x-ratelimit-reset ignored when x-ratelimit-remaining is not 0

### ISSUE THREAD

**Issue by achingbrain** [octokit/plugin-throttling.js#566]
When using `@semantic-release/github` it tries to add a comment to every issue in a released version which uses the issue search.  This API has a very low secondary rate limit - the `403` that comes back when this limit is hit has a `x-ratelimit-reset` header with a date in the future, but a positive `x-ratelimit-remaining` header and no `retry-after` header.

From what I can see, the `x-ratelimit-reset` header is [only used when the `x-ratelimit-remaining` header is 0](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L156-L181) which isn't the case here.

Here is the server response from [this failed build](https://github.com/ipfs/protons/actions/runs/4071758941/jobs/7013934935) including the headers and request ID:

```
[6:16:56 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/protons/protons/node_modules/@octokit/request/dist-node/index.js:86:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/home/runner/work/protons/protons/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3Aipfs%2Fprotons+type%3Apr+is%3Amerged+6f796f1e7dfd631314f9a1df534eabd96dd1528c+229afbcb38ba0edc0622d4c2e97847462b439dc8',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 02 Feb 2023 06:16:56 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '9008:4098:502CA3:5322BE:63DB5558',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '25',
      'x-ratelimit-reset': '1675318655',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '5',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3Aipfs%2Fprotons+type%3Apr+is%3Amerged+6f796f1e7dfd631314f9a1df534eabd96dd1528c+229afbcb38ba0edc0622d4c2e97847462b439dc8',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/18.13.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: undefined,
      hook: [Function: bound bound register],
      retryCount: 4
    }
  },
  pluginName: '[Function: semantic-release-monorepo]'
}
```

I think [this function](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L136) just needs to act on the `x-ratelimit-reset` header if it's present instead of using `x-ratelimit-remaining` as a [proxy](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L158) for detecting `x-ratelimit-reset`, and also before the [check](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L137) for `'secondary rate'` in the error message.

**Comment by achingbrain** [comment]
Just hit this again on another build - would you accept a PR to fix this?

```
[7:27:13 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/progress-events/progress-events/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:78:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3Aachingbrain%2Fprogress-events+type%3Apr+is%3Amerged+4885ab8d48d4569be5d1b124e5ffec5adc09a58d+28550876d5096d95ec937bcc3d668b64db552f74',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 07 Feb 2023 07:27:13 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'E810:8470:CDF5EE:D5C13F:63E1FD50',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '29',
      'x-ratelimit-reset': '1675754893',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3Aachingbrain%2Fprogress-events+type%3Apr+is%3Amerged+4885ab8d48d4569be5d1b124e5ffec5adc09a58d+28550876d5096d95ec937bcc3d668b64db552f74',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.0 Node.js/18.13.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
```

https://github.com/achingbrain/progress-events/actions/runs/4111417492/jobs/7095360239

**Comment by achingbrain** [comment]
> I think [this function](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts?rgh-link-date=2023-02-02T07%3A11%3A18Z#L136) just needs to act on the x-ratelimit-reset header if it's present

Actually I don't think it's that simple, `x-ratelimit-reset` is present in the response to successful responses too.

Maybe the clue is in the existing comment:

```
// The Retry-After header can sometimes be blank when hitting a secondary rate limit,
// but is always present after 2-3s, so make sure to set `retryAfter` to at least 5s by default.
```

Perhaps it needs to use `retry-after` if it's present, if not `x-ratelimit-reset` if it's present, and if not, then fall back to 5s?

**Comment by achingbrain** [comment]
Ok, digging a bit deeper I'm not sure this is even possible to automate around reliably.  According to [this discussion](https://github.com/orgs/community/discussions/24760) when you hit a secondary rate limit and there's no `retry-after` header, you're suppose to just be slower - `"Please create this content at a reasonable pace to avoid further limiting."`

There's no way to calculate what a "reasonable pace" is, it's just an opaque internal GitHub heuristic.  Wonderful.

@gr2m @kfcampbell (I'm tagging you because you contributed to this project recently) have you got any thoughts on how to throttle and not hit the secondary rate limit?  Exponential backoff?  Longer `minimumSecondaryRateRetryAfter` value (currently 5s, maybe should be 30s or even longer)?

**Comment by gr2m** [comment]
> There's no way to calculate what a "reasonable pace" is, it's just an opaque internal GitHub heuristic

It's opaque because the secondary limit is the one protecting GitHub from abusive usage. Basically when the `Retry-After` header is not present, we should treat the response as a secondary rate limit response and act accordingly, which is backing off retries progressively.

It's been a while since I looked into the code, I'll see what I can find out

**Comment by gr2m** [comment]
> I think [this function](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L136) just needs to act on the `x-ratelimit-reset` header if it's present instead of using `x-ratelimit-remaining` as a [proxy](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L158) for detecting `x-ratelimit-reset`, and also before the [check](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L137) for `'secondary rate'` in the error message.

I don't think that makes sense, because one is primary rate limit which is just a numbers game (The `x-ratelimit-*` headers). When you hit the secondary rate limit, you might be blocked altogether in worst cases, it's not related to when the primary rate limit reset is happening.

Any idea how to reliably trigger the secondary rate limit? I'll ask within GitHub if someone can help me with that.

**Comment by gr2m** [comment]
> would you accept a PR to fix this

I'd be happy to work on a PR with you! I've a bit time now and would really like to get this resolved.

I'll try to talk to folks within GitHub to find out what the best strategy for SDKs is in general to handle secondary rate limits, but I think what we can definitely implement is

1. If `Retry-After` is not set, retry at 5s
2. Exponentially increase the timeout until the request goes through successfully.

If you'd like to try to put together a pull request that would be great. No worries if not I hope I'll get to it eventually

**Comment by gr2m** [comment]
> t's not related to when the primary rate limit reset is happening.

I take that back. I just found this in the best practices, I think that is a recent addition

> [If the Retry-After response header is not present] retry your request after the time specified by the x-ratelimit-reset header. The x-ratelimit-reset header will always be an integer representing the time at which the current rate limit window resets in [UTC epoch seconds](http://en.wikipedia.org/wiki/Unix_time).

**Comment by gr2m** [comment]
Actually, let's hold off on that, the "use the x-ratelimit-reset header value as a fallback" recommendation might be outdated. For now, let's just increase the minimal timeout to 60s.
