### ISSUE TITLE
Incorrect types: Could not find a declaration file for module '@octokit/plugin-throttling'

### ISSUE THREAD

**Issue by leeuwd** [octokit/plugin-throttling.js#583]
IDE/buid error when using`@octokit/plugin-throttling@5.1.0` in Next.js 13 and TypeScript 5.0.4:

```
Type error: Could not find a declaration file for module '@octokit/plugin-throttling'. '[redacted]/node_modules/@octokit/plugin-throttling/dist-node/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/octokit__plugin-throttling` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/plugin-throttling';`
```

**Comment by pragmaticivan** [comment]
I can replicate that.

**Comment by wolfy1339** [comment]
There are 2 reasons for this issue.
1. npm changed the file matching code
2. Our build system is no longer maintained and has been archived since April 2022

See https://github.com/npm/cli/issues/6164 and #525 for details
