### ISSUE TITLE
Add Typescript Bindings

### ISSUE THREAD

**Issue by Pandapip1** [octokit/plugin-throttling.js#638]
Pretty simple: add .d.ts declaration files.

**Comment by wolfy1339** [comment]
We have typings already in the published NPM package.

If you are having an issue please be more specific and provide more details.

**Comment by Pandapip1** [comment]
> If you are having an issue please be more specific and provide more details.

Stupid mistake on my part. I forgot to install the package. Sorry for the inconvenience!
