### ISSUE TITLE
Add browser build

### ISSUE THREAD

**Issue by bendtherules** [octokit/plugin-throttling.js#84]
There is no webpack config or build (or something similar) to make sure that it can be imported as npm module for a browser based project.

Even with adding it to webpack build in the consumer project, things like direct json imports makes it very hard to use without adding more plugins in consumer webpack config itself.

**Comment by gr2m** [comment]
Would changing `/lib/triggers-notification-paths.json` to a `.js` file resolve your issue? If you’d like to send a pull request, note that the file is generated by `/scripts/generate-routes.js`, the path and output needs to be updated there.

We are going through the `octokit/*` JavaScript modules and migrating to @pikapkg:
https://gist.github.com/gr2m/5dd2ec6e3a04c3dc79f0cbb46decbe46. It has a browser build, too.

If you like you can send a PR to making the changes?

**Comment by SGrondin** [comment]
I've had a lot of success with [Rollup](https://rollupjs.org), it might be worth looking into.

Here's [Bottleneck's ES5 build config](https://github.com/SGrondin/bottleneck/blob/master/rollup.config.es5.js) and [Bottleneck's "light" build config](https://github.com/SGrondin/bottleneck/blob/master/rollup.config.light.js). The light build is used in this octokit/plugin-throttling project. It was fairly easy to setup, compared to Webpack.

I think it's worth looking into!

**Comment by gr2m** [comment]
Pika is using rollup internally

**Comment by bendtherules** [comment]
> Would changing `/lib/triggers-notification-paths.json` to a `.js` file resolve your issue? If you’d like to send a pull request, note that the file is generated by `/scripts/generate-routes.js`, the path and output needs to be updated there.

Hi, i was trying to manually change those in a project using webpack. Json import and object spread syntax was raising error. Changing both in a browser branch can be a temporary fix. 

> We are going through the `octokit/*` JavaScript modules and migrating to @pikapkg:
> https://gist.github.com/gr2m/5dd2ec6e3a04c3dc79f0cbb46decbe46. It has a browser build, too.
> 
> If you like you can send a PR to making the changes?

That sounds good as a permanent solution. 
I would like to give it a try. I'll try to read pika docs and see how its done. 
Can you point to some example octokit repo if it is already using pika? Or anything specific to this project that I should keep in mind.

**Comment by gr2m** [comment]
We’ve already setup Pika for 

- https://github.com/octokit/endpoint.js
- https://github.com/octokit/request.js
- https://github.com/octokit/app.js

Note that they all use Typescript, too. No need to do it for `@octokit/plugin-throttling.js`, so the setup will be slightly different as the Typescript transpilation step is not required. That said, if you are familiar with Typescript, feel free to do that as well :)

**Comment by bendtherules** [comment]
Finally, started making a few changes in https://github.com/bendtherules/plugin-throttling.js/tree/add-pika. Doing the pika build thing for now, will try to add typescript later.

To keep us on same page, these are the changes:
1. Add pika with node and browser build. These are plain builds, not bundles.
2. Handle json import with babel json inline plugin.

**Comment by gr2m** [comment]
> Add pika with node and browser build. These are plain builds, not bundles.

For the web build, you can add the bundle step as well as the plugin to add the field for https://unpkg.com/, so the lib can directly be loaded from there

https://github.com/octokit/endpoint.js/blob/f44b59151d601dc6c5fc600880c73fd5e20ade3c/package.json#L102-L110

> Handle json import with babel json inline plugin

Replace the JSON file with a JS file. Adapt `/scripts/generate-routes.js` accordingly. I think that’s the simplest way to resolve that.

**Comment by bendtherules** [comment]
> Replace the JSON file with a JS file. Adapt `/scripts/generate-routes.js` accordingly. I think that’s the simplest way to resolve that.

I am not sure how that will work without adding octokit/routes as a runtime dependency. We would need some sort of a build pipeline to run the file during build and export the freezed output. How will that work? 

Pika doesn't seem to have a easy way to add custom logic to the pipeline (like webpack) without creating separate plugins.

**Comment by bendtherules** [comment]
> > Add pika with node and browser build. These are plain builds, not bundles.
> 
> For the web build, you can add the bundle step as well as the plugin to add the field for https://unpkg.com/, so the lib can directly be loaded from there

Sure, I will add the bundle step and unpkg.

**Comment by gr2m** [comment]
> We would need some sort of a build pipeline to run the file during build and export the freezed output. How will that work?

That’s what we have already. `@octokit/routes` is a devDependency

https://github.com/octokit/plugin-throttling.js/blob/dc81d0c435c84bad436c679dc09d08d0df0bb9dd/package.json#L41-L44

Each time `@octokit/routes` gets updated, [Greenkeeper](https://greenkeeper.io/) sends a pull request. In that pull request we update the `lib/triggers-notification-paths.json` file

https://github.com/octokit/plugin-throttling.js/blob/dc81d0c435c84bad436c679dc09d08d0df0bb9dd/.travis.yml#L27-L35

So what we need to do is to update the scripts/generate-routes.js file. Right now it updates the `lib/triggers-notification-paths.json` file

https://github.com/octokit/plugin-throttling.js/blob/dc81d0c435c84bad436c679dc09d08d0df0bb9dd/scripts/generate-routes.js#L22

We should rename `lib/triggers-notification-paths.json` to `lib/triggers-notification-paths.js`, add a `module.exports = ` on top and update `scripts/generate-routes.js` to update the new file instead.

Instead of `JSON.stringify()`, you can use the [javascript-stringify](https://www.npmjs.com/package/javascript-stringify) module so that the linter won’t complain

**Comment by gr2m** [comment]
This issue should be resolved now. You can even directly import the plugin from Pika's CDN, see https://github.com/octokit/plugin-throttling.js/#usage
